[package]
name = "rust-algorithms-practice"
version = "0.1.0"
edition = "2021"
authors = ["Leonardo Freua <leonardo.batista.freua@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
